@isTest
private class Test_Greeter_65 {
  @isTest
  static void greet_0() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_1() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_2() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_3() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_4() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_5() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_6() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_7() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_8() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_9() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_10() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_11() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_12() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_13() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_14() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_15() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_16() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_17() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_18() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_19() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_20() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_21() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_22() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_23() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_24() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_25() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_26() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_27() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_28() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_29() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_30() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_31() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_32() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_33() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_34() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_35() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_36() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_37() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_38() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_39() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_40() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_41() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_42() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_43() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_44() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_45() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_46() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_47() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_48() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_49() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_50() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_51() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_52() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_53() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_54() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_55() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_56() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_57() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_58() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_59() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_60() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_61() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_62() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_63() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_64() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_65() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_66() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_67() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_68() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_69() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_70() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_71() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_72() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_73() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_74() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_75() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_76() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_77() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_78() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_79() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_80() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_81() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_82() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_83() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_84() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_85() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_86() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_87() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_88() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_89() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_90() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_91() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_92() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_93() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_94() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_95() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_96() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_97() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_98() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
  @isTest
  static void greet_99() {
    System.assertEquals(Layer_4.greet('John'), 'Hello John');
  }
}